### ISSUE TITLE
Faster Algorithm for #204 (Prime Counting Function)

### ISSUE THREAD

**Issue by ChenDanCMU** [hqztrue/LeetCodeSolutions#6]
I just came across a (theoretically) faster algorithm for counting primes (problem #204):
J. C. Lagarias and A. M. Odlyzko, [Computing π(x)](http://www.dtc.umn.edu/~odlyzko/doc/arch/analytic.pi.of.x.pdf)[: An analytic method](http://www.dtc.umn.edu/~odlyzko/doc/arch/analytic.pi.of.x.pdf), Journal of Algorithms 8 (1987), pp. 173-191.
The time complexity is O(n^(1/2  + eps)) (see the end of section 1), faster than the  O(n^(2/3  + eps)) running time in the current version. 
There is also a Github repo comparing the running time of those algorithms: https://github.com/kimwalisch/primecount
Thanks for the great work!

**Comment by hqztrue** [comment]
Yeah I'm aware of this a few months after I wrote that solution, e.g. I cited this paper in #1175. Let me update the solution for #204, thanks for the reminder.
